sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - composer self-update
  - composer update --prefer-source $PREFER_LOWEST
  - mkdir -p test/_build

script:
  - vendor/bin/phpunit -c ./phpunit.xml
  - vendor/bin/phpcs --standard=PSR2 ./src/

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover test/_build/logs/clover.xml

notifications:
  irc: "irc.freenode.org#zftalk.modules"
  email: false